name: Build Backend Test

on:
  push:
    branches:
      - test

jobs:
  docker-build:
    runs-on: homelab

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mostrar commit
        run: |
          echo "Commit: $FORGEJO_SHA"
          git rev-parse --short HEAD

      - name: Build Docker image
        run: |
          docker build \
            -t puntodeventa-backend:test \
            .

      - name: Verificar imagen
        run: |
          docker image inspect puntodeventa-backend:test
